#!/bin/bash
set -eE -o pipefail

script_dir=$(dirname "$(realpath "$0")")
cd $script_dir/..

version=$(git describe --tags --always)
echo build $version
CGO_ENABLED=0 go build -ldflags="-X main.appVersion=$version" .
