name: ci

on:
  push:
    branches: []
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    - name: chkfmt
      run: scripts/chkfmt

    # - name: tests
    #   run: |
    #     scripts/tests

    - name: xbuild
      run: scripts/xbuild

    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: prerelease-artifacts
        path: dist/*
